name: apiverve_gamecharacter
description: Generate complete RPG-style characters with race, class, background, stats, and personality.
version: 1.1.14
homepage: https://apiverve.com/marketplace/gamecharacter?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/gamecharacter-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
